lversion: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: npm run test
      - run:
          name: Build Project Burgger app
          command: npm run build
      - run:
          name: Deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase use $FIREBASE_ALIAS